import { describe, it, expect } from 'vitest';
import { parseMrUrl, formatComment } from '../ci/mr-comment.js';
import type { LearningDraft, CodebaseSuggestion } from '../types.js';

describe('parseMrUrl', () => {
  it('解析 GitHub PR URL', () => {
    const result = parseMrUrl('https://github.com/owner/repo/pull/42');
    expect(result).toEqual({ provider: 'github', owner: 'owner', repo: 'repo', number: '42' });
  });

  it('解析 TGit MR URL（单层 group）', () => {
    const result = parseMrUrl('https://git.woa.com/team/project/merge_requests/7');
    expect(result).toEqual({ provider: 'tgit', owner: 'team', repo: 'project', number: '7' });
  });

  it('解析 TGit MR URL（多层 group）', () => {
    const result = parseMrUrl('https://git.woa.com/group/sub/project/merge_requests/123');
    expect(result).toEqual({ provider: 'tgit', owner: 'group/sub', repo: 'project', number: '123' });
  });

  it('不支持的 URL 抛出错误', () => {
    expect(() => parseMrUrl('https://gitlab.com/org/repo/-/merge_requests/1')).toThrow('无法解析 MR URL');
  });
});

describe('formatComment', () => {
  const marker = '<!-- teamai:ci-extract -->';

  it('格式化含 learning 和 suggestions 的 comment', () => {
    const learning: LearningDraft = {
      title: '修复数据库连接泄漏',
      content: '---\ntitle: 修复数据库连接泄漏\n---\n\n## 背景\n连接未关闭',
    };
    const suggestions: CodebaseSuggestion[] = [
      { section: '架构', action: 'update', content: '新增连接池管理模块' },
    ];

    const result = formatComment(learning, suggestions, marker);

    expect(result).toContain(marker);
    expect(result).toContain('修复数据库连接泄漏');
    expect(result).toContain('### Learning');
    expect(result).toContain('### Codebase.md 更新建议');
    expect(result).toContain('| 架构 | update |');
    expect(result).toContain('Auto-generated by');
  });

  it('无 learning 和 suggestions 时显示"无可提炼"', () => {
    const result = formatComment(undefined, undefined, marker);
    expect(result).toContain(marker);
    expect(result).toContain('无可提炼的知识内容');
    expect(result).not.toContain('### Learning');
  });

  it('仅有 learning 无 suggestions', () => {
    const learning: LearningDraft = {
      title: '测试标题',
      content: '内容',
    };
    const result = formatComment(learning, [], marker);
    expect(result).toContain('### Learning');
    expect(result).not.toContain('### Codebase.md 更新建议');
  });
});
